package bizcode

import "goshop/pkg/errors"

func init() {
	register(ErrConnectDB, errors.KindUnavailable, "Init db error")
	register(ErrConnectGRPC, errors.KindUnavailable, "Connect to grpc error")
	register(ErrUserNotFound, errors.KindNotFound, "User not found")
	register(ErrUserAlreadyExists, errors.KindConflict, "User already exists")
	register(ErrUserPasswordIncorrect, errors.KindUnauthenticated, "User password incorrect")
	register(ErrSmsSend, errors.KindUnavailable, "Send sms error")
	register(ErrCodeNotExist, errors.KindInvalidArgument, "Sms code incorrect or expired")
	register(ErrCodeInCorrect, errors.KindInvalidArgument, "Sms code incorrect")
	register(ErrUserLoginLocked, errors.KindRateLimited, "User login temporarily locked")
	register(ErrSmsRateLimited, errors.KindRateLimited, "Sms send temporarily rate limited")
	register(ErrSmsVerifyLocked, errors.KindRateLimited, "Sms verification temporarily locked")
	register(ErrUserAccountInactive, errors.KindPermissionDenied, "User account is not active")
	register(ErrAccountDeletionBlocked, errors.KindConflict, "Account has unfinished orders, refunds, or after-sales cases")
	register(ErrEmailVerificationUnavailable, errors.KindUnavailable, "Email verification temporarily unavailable")
	register(ErrGoodsNotFound, errors.KindNotFound, "Goods not found")
	register(ErrGoodsInvalid, errors.KindInvalidArgument, "Goods request is invalid")
	register(ErrCategoryNotFound, errors.KindNotFound, "Category not found")
	register(ErrBrandNotFound, errors.KindNotFound, "Brand not found")
	register(ErrBannerNotFound, errors.KindNotFound, "Banner not found")
	register(ErrCategoryBrandNotFound, errors.KindNotFound, "Category brand relation not found")
	register(ErrEsUnmarshal, errors.KindInternal, "Es unmarshal error")
	register(ErrInventoryNotFound, errors.KindNotFound, "Inventory not found")
	register(ErrInvSellDetailNotFound, errors.KindInvalidArgument, "Inventory sell detail not found")
	register(ErrInvNotEnough, errors.KindConflict, "Inventory not enough")
	register(ErrShopCartItemNotFound, errors.KindNotFound, "ShopCart item not found")
	register(ErrSubmitOrder, errors.KindConflict, "Submit order error")
	register(ErrNoGoodsSelect, errors.KindInvalidArgument, "No Goods selected")
	register(ErrOrderNotFound, errors.KindNotFound, "Order not found")
	register(ErrOrderConflict, errors.KindConflict, "Order already exists with different data")
	register(ErrOrderStatusInvalid, errors.KindConflict, "Order status is invalid")
}
