// Code generated by protoc-gen-go-gin. DO NOT EDIT.

package v1

import (
	gin "github.com/gin-gonic/gin"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
)

type UserHttpServer struct {
	server UserServer
	router gin.IRouter
}

func RegisterUserServerHTTPServer(srv UserServer, r gin.IRouter) {
	s := UserHttpServer{
		server: srv,
		router: r,
	}
	s.RegisterService()
}

func (s *UserHttpServer) GetUserList_0(c *gin.Context) {
	var in PageInfo

	if err := c.ShouldBindJSON(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	out, err := s.server.GetUserList(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *UserHttpServer) GetUserByMobile_0(c *gin.Context) {
	var in MobileRequest

	if err := c.ShouldBindJSON(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	out, err := s.server.GetUserByMobile(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *UserHttpServer) GetUserById_0(c *gin.Context) {
	var in IdRequest

	if err := c.ShouldBindJSON(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	out, err := s.server.GetUserById(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *UserHttpServer) UpdateUserStatus_0(c *gin.Context) {
	var in UpdateUserStatusRequest

	if err := c.ShouldBindJSON(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	out, err := s.server.UpdateUserStatus(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *UserHttpServer) ListStaffRoles_0(c *gin.Context) {
	var in emptypb.Empty

	if err := c.ShouldBindJSON(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	out, err := s.server.ListStaffRoles(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *UserHttpServer) GetUserStaffRoles_0(c *gin.Context) {
	var in IdRequest

	if err := c.ShouldBindJSON(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	out, err := s.server.GetUserStaffRoles(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *UserHttpServer) ReplaceUserStaffRoles_0(c *gin.Context) {
	var in ReplaceUserStaffRolesRequest

	if err := c.ShouldBindJSON(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	out, err := s.server.ReplaceUserStaffRoles(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *UserHttpServer) GetUserAuthByMobile_0(c *gin.Context) {
	var in MobileRequest

	if err := c.ShouldBindJSON(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	out, err := s.server.GetUserAuthByMobile(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *UserHttpServer) GetUserAuthById_0(c *gin.Context) {
	var in IdRequest

	if err := c.ShouldBindJSON(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	out, err := s.server.GetUserAuthById(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *UserHttpServer) CreateUser_0(c *gin.Context) {
	var in CreateUserInfo

	if err := c.ShouldBindJSON(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	out, err := s.server.CreateUser(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *UserHttpServer) UpdateUser_0(c *gin.Context) {
	var in UpdateUserInfo

	if err := c.ShouldBindJSON(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	out, err := s.server.UpdateUser(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *UserHttpServer) DeleteUser_0(c *gin.Context) {
	var in IdRequest

	if err := c.ShouldBindJSON(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	out, err := s.server.DeleteUser(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *UserHttpServer) CheckPassWord_0(c *gin.Context) {
	var in PasswordCheckInfo

	if err := c.ShouldBindJSON(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	out, err := s.server.CheckPassWord(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *UserHttpServer) RegisterService() {

	s.router.Handle("POST", "/v1/users", s.GetUserList_0)

	s.router.Handle("POST", "/v1/user/mobile", s.GetUserByMobile_0)

	s.router.Handle("POST", "/v1/user/id", s.GetUserById_0)

	s.router.Handle("POST", "", s.UpdateUserStatus_0)

	s.router.Handle("POST", "", s.ListStaffRoles_0)

	s.router.Handle("POST", "", s.GetUserStaffRoles_0)

	s.router.Handle("POST", "", s.ReplaceUserStaffRoles_0)

	s.router.Handle("POST", "", s.GetUserAuthByMobile_0)

	s.router.Handle("POST", "", s.GetUserAuthById_0)

	s.router.Handle("POST", "/v1/user/create", s.CreateUser_0)

	s.router.Handle("POST", "/v1/user/update", s.UpdateUser_0)

	s.router.Handle("POST", "/v1/user/{id}", s.DeleteUser_0)

	s.router.Handle("POST", "/v1/user/password", s.CheckPassWord_0)

}
