-- Formal DB-backed RBAC seed. No bootstrap/config role is created here.
INSERT IGNORE INTO roles (name, description) VALUES
  ('support', '客户支持运营权限'), ('ops', '运营管理权限'),
  ('finance', '支付与退款操作权限'), ('catalog', '目录和库存维护权限'),
  ('review', '评论审核和商家回复权限'), ('admin', '有限后台管理权限'),
  ('super_admin', '全量后台管理权限');
INSERT IGNORE INTO role_domains (role_id, domain) SELECT id, CASE name WHEN 'support' THEN 'support' WHEN 'ops' THEN 'operations' ELSE name END FROM roles WHERE name IN ('support','ops','finance','catalog','review');
INSERT IGNORE INTO role_domains (role_id, domain) SELECT id, 'platform' FROM roles WHERE name IN ('admin','super_admin');
INSERT IGNORE INTO role_permissions (role_id, permission)
SELECT r.id, p.permission FROM roles r JOIN (
  SELECT 'support' role_name, 'role:read:any' permission UNION ALL SELECT 'support','user:list:any' UNION ALL SELECT 'support','user:read:any' UNION ALL SELECT 'support','order:read:any' UNION ALL SELECT 'support','audit:read:any'
  UNION ALL SELECT 'ops','inventory:read:any' UNION ALL SELECT 'ops','inventory:write:any' UNION ALL SELECT 'ops','inventory:audit:read:any' UNION ALL SELECT 'ops','order:read:any' UNION ALL SELECT 'ops','order:close:any' UNION ALL SELECT 'ops','audit:read:any'
  UNION ALL SELECT 'finance','order:read:any' UNION ALL SELECT 'finance','order:refund:any' UNION ALL SELECT 'finance','payment:reconciliation:read:any' UNION ALL SELECT 'finance','refund:dead_job:retry:any' UNION ALL SELECT 'finance','audit:read:any'
  UNION ALL SELECT 'catalog','goods:read:any' UNION ALL SELECT 'catalog','goods:write:any'
  UNION ALL SELECT 'review','review:moderate:any' UNION ALL SELECT 'review','review:reply:any'
  UNION ALL SELECT 'admin','role:read:any' UNION ALL SELECT 'admin','user:create:any' UNION ALL SELECT 'admin','user:list:any' UNION ALL SELECT 'admin','user:read:any' UNION ALL SELECT 'admin','user:disable:any' UNION ALL SELECT 'admin','goods:read:any' UNION ALL SELECT 'admin','goods:write:any' UNION ALL SELECT 'admin','inventory:read:any' UNION ALL SELECT 'admin','inventory:write:any' UNION ALL SELECT 'admin','inventory:audit:read:any' UNION ALL SELECT 'admin','order:read:any' UNION ALL SELECT 'admin','order:close:any' UNION ALL SELECT 'admin','order:refund:any' UNION ALL SELECT 'admin','staff_session:read:any' UNION ALL SELECT 'admin','staff_session:revoke:any' UNION ALL SELECT 'admin','break_glass:approve:any' UNION ALL SELECT 'admin','payment:reconciliation:read:any' UNION ALL SELECT 'admin','refund:dead_job:retry:any' UNION ALL SELECT 'admin','audit:read:any' UNION ALL SELECT 'admin','review:moderate:any' UNION ALL SELECT 'admin','review:reply:any' UNION ALL SELECT 'admin','review:aggregate:rebuild:any'
  UNION ALL SELECT 'super_admin','role:read:any' UNION ALL SELECT 'super_admin','role:assign:any' UNION ALL SELECT 'super_admin','role:write:any' UNION ALL SELECT 'super_admin','user:create:any' UNION ALL SELECT 'super_admin','user:list:any' UNION ALL SELECT 'super_admin','user:read:any' UNION ALL SELECT 'super_admin','user:disable:any' UNION ALL SELECT 'super_admin','goods:read:any' UNION ALL SELECT 'super_admin','goods:write:any' UNION ALL SELECT 'super_admin','inventory:read:any' UNION ALL SELECT 'super_admin','inventory:write:any' UNION ALL SELECT 'super_admin','inventory:audit:read:any' UNION ALL SELECT 'super_admin','order:read:any' UNION ALL SELECT 'super_admin','order:close:any' UNION ALL SELECT 'super_admin','order:refund:any' UNION ALL SELECT 'super_admin','staff_session:read:any' UNION ALL SELECT 'super_admin','staff_session:revoke:any' UNION ALL SELECT 'super_admin','break_glass:approve:any' UNION ALL SELECT 'super_admin','payment:reconciliation:read:any' UNION ALL SELECT 'super_admin','refund:dead_job:retry:any' UNION ALL SELECT 'super_admin','payment:callback:simulate' UNION ALL SELECT 'super_admin','audit:read:any' UNION ALL SELECT 'super_admin','review:moderate:any' UNION ALL SELECT 'super_admin','review:reply:any' UNION ALL SELECT 'super_admin','review:aggregate:rebuild:any'
) p ON p.role_name = r.name;
