version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - goconst
run:
  timeout: 2m
linters-settings:
  staticcheck:
    checks:
      - all
      - "-SA1019"
exclusions:
  paths:
    - vendor
    - testdata
