// Command protoc-gen-go-gin generates the small Gin wrappers used by this
// repository's checked-in *_gin.pb.go files.
package main

import (
	"flag"

	"google.golang.org/genproto/googleapis/api/annotations"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
)

const generatedFilenameSuffix = "_gin.pb.go"

var (
	ginPackage  = protogen.GoImportPath("github.com/gin-gonic/gin")
	httpPackage = protogen.GoImportPath("net/http")
)

func main() {
	var flags flag.FlagSet
	protogen.Options{ParamFunc: flags.Set}.Run(func(plugin *protogen.Plugin) error {
		for _, file := range plugin.Files {
			if file.Generate {
				generateFile(plugin, file)
			}
		}
		return nil
	})
}

func generateFile(plugin *protogen.Plugin, file *protogen.File) {
	if len(file.Services) == 0 {
		return
	}

	filename := file.GeneratedFilenamePrefix + generatedFilenameSuffix
	g := plugin.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-go-gin. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	for _, service := range file.Services {
		generateService(g, service)
	}
}

func generateService(g *protogen.GeneratedFile, service *protogen.Service) {
	serverType := service.GoName + "HttpServer"

	g.P("type ", serverType, " struct {")
	g.P("server ", service.GoName, "Server")
	g.P("router ", g.QualifiedGoIdent(ginPackage.Ident("IRouter")))
	g.P("}")
	g.P()

	g.P("func Register", service.GoName, "ServerHTTPServer(srv ", service.GoName, "Server, r ", g.QualifiedGoIdent(ginPackage.Ident("IRouter")), ") {")
	g.P("s := ", serverType, "{")
	g.P("server: srv,")
	g.P("router: r,")
	g.P("}")
	g.P("s.RegisterService()")
	g.P("}")
	g.P()

	for _, method := range service.Methods {
		generateMethod(g, serverType, method)
	}

	g.P("func (s *", serverType, ") RegisterService() {")
	g.P()
	for _, method := range service.Methods {
		g.P(`s.router.Handle("POST", "`, httpPath(method), `", s.`, method.GoName, "_0)")
		g.P()
	}
	g.P("}")
}

func generateMethod(g *protogen.GeneratedFile, serverType string, method *protogen.Method) {
	input := g.QualifiedGoIdent(method.Input.GoIdent)

	g.P("func (s *", serverType, ") ", method.GoName, "_0(c *", g.QualifiedGoIdent(ginPackage.Ident("Context")), ") {")
	g.P("var in ", input)
	g.P()
	g.P("if err := c.ShouldBindJSON(&in); err != nil {")
	g.P("c.JSON(", g.QualifiedGoIdent(httpPackage.Ident("StatusBadRequest")), ", ", g.QualifiedGoIdent(ginPackage.Ident("H")), `{ "error": err.Error() })`)
	g.P("return")
	g.P("}")
	g.P()
	g.P("out, err := s.server.", method.GoName, "(c, &in)")
	g.P("if err != nil {")
	g.P("c.JSON(", g.QualifiedGoIdent(httpPackage.Ident("StatusInternalServerError")), ", ", g.QualifiedGoIdent(ginPackage.Ident("H")), `{ "error": err.Error() })`)
	g.P("return")
	g.P("}")
	g.P()
	g.P("c.JSON(", g.QualifiedGoIdent(httpPackage.Ident("StatusOK")), ", out)")
	g.P("}")
	g.P()
}

func httpPath(method *protogen.Method) string {
	rule := proto.GetExtension(method.Desc.Options(), annotations.E_Http)
	httpRule, ok := rule.(*annotations.HttpRule)
	if !ok || httpRule == nil {
		return ""
	}

	switch pattern := httpRule.Pattern.(type) {
	case *annotations.HttpRule_Get:
		return pattern.Get
	case *annotations.HttpRule_Post:
		return pattern.Post
	case *annotations.HttpRule_Put:
		return pattern.Put
	case *annotations.HttpRule_Delete:
		return pattern.Delete
	case *annotations.HttpRule_Patch:
		return pattern.Patch
	case *annotations.HttpRule_Custom:
		if pattern.Custom == nil {
			return ""
		}
		return pattern.Custom.Path
	default:
		return ""
	}
}
