// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: order.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentEventRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Provider          string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	EventId           string                 `protobuf:"bytes,2,opt,name=eventId,proto3" json:"eventId,omitempty"`
	OrderSn           string                 `protobuf:"bytes,3,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	TradeNo           string                 `protobuf:"bytes,4,opt,name=tradeNo,proto3" json:"tradeNo,omitempty"`
	EventType         string                 `protobuf:"bytes,5,opt,name=eventType,proto3" json:"eventType,omitempty"`
	ProviderAmountFen int64                  `protobuf:"varint,6,opt,name=providerAmountFen,proto3" json:"providerAmountFen,omitempty"`
	RefundAmountFen   int64                  `protobuf:"varint,7,opt,name=refundAmountFen,proto3" json:"refundAmountFen,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PaymentEventRequest) Reset() {
	*x = PaymentEventRequest{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentEventRequest) ProtoMessage() {}

func (x *PaymentEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentEventRequest.ProtoReflect.Descriptor instead.
func (*PaymentEventRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentEventRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *PaymentEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *PaymentEventRequest) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *PaymentEventRequest) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *PaymentEventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *PaymentEventRequest) GetProviderAmountFen() int64 {
	if x != nil {
		return x.ProviderAmountFen
	}
	return 0
}

func (x *PaymentEventRequest) GetRefundAmountFen() int64 {
	if x != nil {
		return x.RefundAmountFen
	}
	return 0
}

type PaymentEventResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Accepted       bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Completed      bool                   `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
	OrderAmountFen int64                  `protobuf:"varint,4,opt,name=orderAmountFen,proto3" json:"orderAmountFen,omitempty"`
	OrderStatus    string                 `protobuf:"bytes,5,opt,name=orderStatus,proto3" json:"orderStatus,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PaymentEventResponse) Reset() {
	*x = PaymentEventResponse{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentEventResponse) ProtoMessage() {}

func (x *PaymentEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentEventResponse.ProtoReflect.Descriptor instead.
func (*PaymentEventResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentEventResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PaymentEventResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *PaymentEventResponse) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *PaymentEventResponse) GetOrderAmountFen() int64 {
	if x != nil {
		return x.OrderAmountFen
	}
	return 0
}

func (x *PaymentEventResponse) GetOrderStatus() string {
	if x != nil {
		return x.OrderStatus
	}
	return ""
}

type CompletePaymentEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorDetail   string                 `protobuf:"bytes,3,opt,name=errorDetail,proto3" json:"errorDetail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletePaymentEventRequest) Reset() {
	*x = CompletePaymentEventRequest{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletePaymentEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletePaymentEventRequest) ProtoMessage() {}

func (x *CompletePaymentEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletePaymentEventRequest.ProtoReflect.Descriptor instead.
func (*CompletePaymentEventRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *CompletePaymentEventRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CompletePaymentEventRequest) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CompletePaymentEventRequest) GetErrorDetail() string {
	if x != nil {
		return x.ErrorDetail
	}
	return ""
}

type PaymentEventListRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderSn        string                 `protobuf:"bytes,1,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	Page           int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize       int32                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	MismatchesOnly bool                   `protobuf:"varint,4,opt,name=mismatchesOnly,proto3" json:"mismatchesOnly,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PaymentEventListRequest) Reset() {
	*x = PaymentEventListRequest{}
	mi := &file_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentEventListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentEventListRequest) ProtoMessage() {}

func (x *PaymentEventListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentEventListRequest.ProtoReflect.Descriptor instead.
func (*PaymentEventListRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

func (x *PaymentEventListRequest) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *PaymentEventListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaymentEventListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PaymentEventListRequest) GetMismatchesOnly() bool {
	if x != nil {
		return x.MismatchesOnly
	}
	return false
}

type PaymentEventRecord struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Provider          string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	EventId           string                 `protobuf:"bytes,3,opt,name=eventId,proto3" json:"eventId,omitempty"`
	OrderSn           string                 `protobuf:"bytes,4,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	TradeNo           string                 `protobuf:"bytes,5,opt,name=tradeNo,proto3" json:"tradeNo,omitempty"`
	EventType         string                 `protobuf:"bytes,6,opt,name=eventType,proto3" json:"eventType,omitempty"`
	OrderAmountFen    int64                  `protobuf:"varint,7,opt,name=orderAmountFen,proto3" json:"orderAmountFen,omitempty"`
	ProviderAmountFen int64                  `protobuf:"varint,8,opt,name=providerAmountFen,proto3" json:"providerAmountFen,omitempty"`
	RefundAmountFen   int64                  `protobuf:"varint,9,opt,name=refundAmountFen,proto3" json:"refundAmountFen,omitempty"`
	Status            string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	ErrorDetail       string                 `protobuf:"bytes,11,opt,name=errorDetail,proto3" json:"errorDetail,omitempty"`
	ReceivedAt        int64                  `protobuf:"varint,12,opt,name=receivedAt,proto3" json:"receivedAt,omitempty"`
	CompletedAt       int64                  `protobuf:"varint,13,opt,name=completedAt,proto3" json:"completedAt,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PaymentEventRecord) Reset() {
	*x = PaymentEventRecord{}
	mi := &file_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentEventRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentEventRecord) ProtoMessage() {}

func (x *PaymentEventRecord) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentEventRecord.ProtoReflect.Descriptor instead.
func (*PaymentEventRecord) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

func (x *PaymentEventRecord) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PaymentEventRecord) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *PaymentEventRecord) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *PaymentEventRecord) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *PaymentEventRecord) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *PaymentEventRecord) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *PaymentEventRecord) GetOrderAmountFen() int64 {
	if x != nil {
		return x.OrderAmountFen
	}
	return 0
}

func (x *PaymentEventRecord) GetProviderAmountFen() int64 {
	if x != nil {
		return x.ProviderAmountFen
	}
	return 0
}

func (x *PaymentEventRecord) GetRefundAmountFen() int64 {
	if x != nil {
		return x.RefundAmountFen
	}
	return 0
}

func (x *PaymentEventRecord) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PaymentEventRecord) GetErrorDetail() string {
	if x != nil {
		return x.ErrorDetail
	}
	return ""
}

func (x *PaymentEventRecord) GetReceivedAt() int64 {
	if x != nil {
		return x.ReceivedAt
	}
	return 0
}

func (x *PaymentEventRecord) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

type PaymentEventListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data          []*PaymentEventRecord  `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	MismatchCount int32                  `protobuf:"varint,3,opt,name=mismatchCount,proto3" json:"mismatchCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentEventListResponse) Reset() {
	*x = PaymentEventListResponse{}
	mi := &file_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentEventListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentEventListResponse) ProtoMessage() {}

func (x *PaymentEventListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentEventListResponse.ProtoReflect.Descriptor instead.
func (*PaymentEventListResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{5}
}

func (x *PaymentEventListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PaymentEventListResponse) GetData() []*PaymentEventRecord {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PaymentEventListResponse) GetMismatchCount() int32 {
	if x != nil {
		return x.MismatchCount
	}
	return 0
}

type ClaimRefundJobsRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Limit              int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	MaxAttempts        int32                  `protobuf:"varint,2,opt,name=maxAttempts,proto3" json:"maxAttempts,omitempty"`
	LockTimeoutSeconds int64                  `protobuf:"varint,3,opt,name=lockTimeoutSeconds,proto3" json:"lockTimeoutSeconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ClaimRefundJobsRequest) Reset() {
	*x = ClaimRefundJobsRequest{}
	mi := &file_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimRefundJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimRefundJobsRequest) ProtoMessage() {}

func (x *ClaimRefundJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimRefundJobsRequest.ProtoReflect.Descriptor instead.
func (*ClaimRefundJobsRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6}
}

func (x *ClaimRefundJobsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ClaimRefundJobsRequest) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *ClaimRefundJobsRequest) GetLockTimeoutSeconds() int64 {
	if x != nil {
		return x.LockTimeoutSeconds
	}
	return 0
}

type RefundJob struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RefundRequestId int64                  `protobuf:"varint,2,opt,name=refundRequestId,proto3" json:"refundRequestId,omitempty"`
	OrderSn         string                 `protobuf:"bytes,3,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	TradeNo         string                 `protobuf:"bytes,4,opt,name=tradeNo,proto3" json:"tradeNo,omitempty"`
	AmountFen       int64                  `protobuf:"varint,5,opt,name=amountFen,proto3" json:"amountFen,omitempty"`
	Reason          string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	CorrelationId   string                 `protobuf:"bytes,7,opt,name=correlationId,proto3" json:"correlationId,omitempty"`
	Attempts        int32                  `protobuf:"varint,8,opt,name=attempts,proto3" json:"attempts,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RefundJob) Reset() {
	*x = RefundJob{}
	mi := &file_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundJob) ProtoMessage() {}

func (x *RefundJob) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundJob.ProtoReflect.Descriptor instead.
func (*RefundJob) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{7}
}

func (x *RefundJob) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RefundJob) GetRefundRequestId() int64 {
	if x != nil {
		return x.RefundRequestId
	}
	return 0
}

func (x *RefundJob) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *RefundJob) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *RefundJob) GetAmountFen() int64 {
	if x != nil {
		return x.AmountFen
	}
	return 0
}

func (x *RefundJob) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RefundJob) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *RefundJob) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

type ClaimRefundJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*RefundJob           `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimRefundJobsResponse) Reset() {
	*x = ClaimRefundJobsResponse{}
	mi := &file_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimRefundJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimRefundJobsResponse) ProtoMessage() {}

func (x *ClaimRefundJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimRefundJobsResponse.ProtoReflect.Descriptor instead.
func (*ClaimRefundJobsResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{8}
}

func (x *ClaimRefundJobsResponse) GetJobs() []*RefundJob {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type CompleteRefundJobRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Success          bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Provider         string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	ProviderRefundId string                 `protobuf:"bytes,4,opt,name=providerRefundId,proto3" json:"providerRefundId,omitempty"`
	ProviderStatus   string                 `protobuf:"bytes,5,opt,name=providerStatus,proto3" json:"providerStatus,omitempty"`
	ErrorDetail      string                 `protobuf:"bytes,6,opt,name=errorDetail,proto3" json:"errorDetail,omitempty"`
	MaxAttempts      int32                  `protobuf:"varint,7,opt,name=maxAttempts,proto3" json:"maxAttempts,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CompleteRefundJobRequest) Reset() {
	*x = CompleteRefundJobRequest{}
	mi := &file_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteRefundJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteRefundJobRequest) ProtoMessage() {}

func (x *CompleteRefundJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteRefundJobRequest.ProtoReflect.Descriptor instead.
func (*CompleteRefundJobRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{9}
}

func (x *CompleteRefundJobRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CompleteRefundJobRequest) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CompleteRefundJobRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CompleteRefundJobRequest) GetProviderRefundId() string {
	if x != nil {
		return x.ProviderRefundId
	}
	return ""
}

func (x *CompleteRefundJobRequest) GetProviderStatus() string {
	if x != nil {
		return x.ProviderStatus
	}
	return ""
}

func (x *CompleteRefundJobRequest) GetErrorDetail() string {
	if x != nil {
		return x.ErrorDetail
	}
	return ""
}

func (x *CompleteRefundJobRequest) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

type ProviderTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=eventId,proto3" json:"eventId,omitempty"`
	OrderSn       string                 `protobuf:"bytes,2,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	TradeNo       string                 `protobuf:"bytes,3,opt,name=tradeNo,proto3" json:"tradeNo,omitempty"`
	EventType     string                 `protobuf:"bytes,4,opt,name=eventType,proto3" json:"eventType,omitempty"`
	AmountFen     int64                  `protobuf:"varint,5,opt,name=amountFen,proto3" json:"amountFen,omitempty"`
	OccurredAt    int64                  `protobuf:"varint,6,opt,name=occurredAt,proto3" json:"occurredAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderTransaction) Reset() {
	*x = ProviderTransaction{}
	mi := &file_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderTransaction) ProtoMessage() {}

func (x *ProviderTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderTransaction.ProtoReflect.Descriptor instead.
func (*ProviderTransaction) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{10}
}

func (x *ProviderTransaction) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ProviderTransaction) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *ProviderTransaction) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *ProviderTransaction) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ProviderTransaction) GetAmountFen() int64 {
	if x != nil {
		return x.AmountFen
	}
	return 0
}

func (x *ProviderTransaction) GetOccurredAt() int64 {
	if x != nil {
		return x.OccurredAt
	}
	return 0
}

type ReconcilePaymentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	WindowStart   int64                  `protobuf:"varint,2,opt,name=windowStart,proto3" json:"windowStart,omitempty"`
	WindowEnd     int64                  `protobuf:"varint,3,opt,name=windowEnd,proto3" json:"windowEnd,omitempty"`
	Transactions  []*ProviderTransaction `protobuf:"bytes,4,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcilePaymentsRequest) Reset() {
	*x = ReconcilePaymentsRequest{}
	mi := &file_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcilePaymentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcilePaymentsRequest) ProtoMessage() {}

func (x *ReconcilePaymentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcilePaymentsRequest.ProtoReflect.Descriptor instead.
func (*ReconcilePaymentsRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{11}
}

func (x *ReconcilePaymentsRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ReconcilePaymentsRequest) GetWindowStart() int64 {
	if x != nil {
		return x.WindowStart
	}
	return 0
}

func (x *ReconcilePaymentsRequest) GetWindowEnd() int64 {
	if x != nil {
		return x.WindowEnd
	}
	return 0
}

func (x *ReconcilePaymentsRequest) GetTransactions() []*ProviderTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type ReconcilePaymentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         int64                  `protobuf:"varint,1,opt,name=runId,proto3" json:"runId,omitempty"`
	CheckedCount  int32                  `protobuf:"varint,2,opt,name=checkedCount,proto3" json:"checkedCount,omitempty"`
	MismatchCount int32                  `protobuf:"varint,3,opt,name=mismatchCount,proto3" json:"mismatchCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcilePaymentsResponse) Reset() {
	*x = ReconcilePaymentsResponse{}
	mi := &file_order_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcilePaymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcilePaymentsResponse) ProtoMessage() {}

func (x *ReconcilePaymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcilePaymentsResponse.ProtoReflect.Descriptor instead.
func (*ReconcilePaymentsResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{12}
}

func (x *ReconcilePaymentsResponse) GetRunId() int64 {
	if x != nil {
		return x.RunId
	}
	return 0
}

func (x *ReconcilePaymentsResponse) GetCheckedCount() int32 {
	if x != nil {
		return x.CheckedCount
	}
	return 0
}

func (x *ReconcilePaymentsResponse) GetMismatchCount() int32 {
	if x != nil {
		return x.MismatchCount
	}
	return 0
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_order_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{13}
}

func (x *UserInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type OrderStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderSn         string                 `protobuf:"bytes,2,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	Status          string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	PayType         string                 `protobuf:"bytes,4,opt,name=payType,proto3" json:"payType,omitempty"`
	TradeNo         string                 `protobuf:"bytes,5,opt,name=tradeNo,proto3" json:"tradeNo,omitempty"`
	PayTime         int64                  `protobuf:"varint,6,opt,name=payTime,proto3" json:"payTime,omitempty"`
	ActorUserId     int32                  `protobuf:"varint,7,opt,name=actorUserId,proto3" json:"actorUserId,omitempty"`
	RefundAmountFen int64                  `protobuf:"varint,8,opt,name=refundAmountFen,proto3" json:"refundAmountFen,omitempty"`
	Reason          string                 `protobuf:"bytes,9,opt,name=reason,proto3" json:"reason,omitempty"`
	CorrelationId   string                 `protobuf:"bytes,10,opt,name=correlationId,proto3" json:"correlationId,omitempty"`
	RequestId       string                 `protobuf:"bytes,11,opt,name=requestId,proto3" json:"requestId,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OrderStatus) Reset() {
	*x = OrderStatus{}
	mi := &file_order_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStatus) ProtoMessage() {}

func (x *OrderStatus) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStatus.ProtoReflect.Descriptor instead.
func (*OrderStatus) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{14}
}

func (x *OrderStatus) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderStatus) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *OrderStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderStatus) GetPayType() string {
	if x != nil {
		return x.PayType
	}
	return ""
}

func (x *OrderStatus) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *OrderStatus) GetPayTime() int64 {
	if x != nil {
		return x.PayTime
	}
	return 0
}

func (x *OrderStatus) GetActorUserId() int32 {
	if x != nil {
		return x.ActorUserId
	}
	return 0
}

func (x *OrderStatus) GetRefundAmountFen() int64 {
	if x != nil {
		return x.RefundAmountFen
	}
	return 0
}

func (x *OrderStatus) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *OrderStatus) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *OrderStatus) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type CartItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	GoodsId       int32                  `protobuf:"varint,3,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	GoodsName     string                 `protobuf:"bytes,4,opt,name=goodsName,proto3" json:"goodsName,omitempty"`
	GoodsImage    string                 `protobuf:"bytes,5,opt,name=goodsImage,proto3" json:"goodsImage,omitempty"`
	Nums          int32                  `protobuf:"varint,7,opt,name=nums,proto3" json:"nums,omitempty"`
	Checked       bool                   `protobuf:"varint,8,opt,name=checked,proto3" json:"checked,omitempty"`
	GoodsPriceFen int64                  `protobuf:"varint,9,opt,name=goodsPriceFen,proto3" json:"goodsPriceFen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItemRequest) Reset() {
	*x = CartItemRequest{}
	mi := &file_order_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItemRequest) ProtoMessage() {}

func (x *CartItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItemRequest.ProtoReflect.Descriptor instead.
func (*CartItemRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{15}
}

func (x *CartItemRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CartItemRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CartItemRequest) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *CartItemRequest) GetGoodsName() string {
	if x != nil {
		return x.GoodsName
	}
	return ""
}

func (x *CartItemRequest) GetGoodsImage() string {
	if x != nil {
		return x.GoodsImage
	}
	return ""
}

func (x *CartItemRequest) GetNums() int32 {
	if x != nil {
		return x.Nums
	}
	return 0
}

func (x *CartItemRequest) GetChecked() bool {
	if x != nil {
		return x.Checked
	}
	return false
}

func (x *CartItemRequest) GetGoodsPriceFen() int64 {
	if x != nil {
		return x.GoodsPriceFen
	}
	return 0
}

type OrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Mobile        string                 `protobuf:"bytes,5,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Post          string                 `protobuf:"bytes,6,opt,name=post,proto3" json:"post,omitempty"`
	OrderSn       string                 `protobuf:"bytes,7,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	OrderItems    []*OrderItemResponse   `protobuf:"bytes,8,rep,name=orderItems,proto3" json:"orderItems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderRequest) Reset() {
	*x = OrderRequest{}
	mi := &file_order_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRequest) ProtoMessage() {}

func (x *OrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRequest.ProtoReflect.Descriptor instead.
func (*OrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{16}
}

func (x *OrderRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *OrderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *OrderRequest) GetPost() string {
	if x != nil {
		return x.Post
	}
	return ""
}

func (x *OrderRequest) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *OrderRequest) GetOrderItems() []*OrderItemResponse {
	if x != nil {
		return x.OrderItems
	}
	return nil
}

type OrderLookupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderSn       string                 `protobuf:"bytes,1,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderLookupRequest) Reset() {
	*x = OrderLookupRequest{}
	mi := &file_order_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderLookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderLookupRequest) ProtoMessage() {}

func (x *OrderLookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderLookupRequest.ProtoReflect.Descriptor instead.
func (*OrderLookupRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{17}
}

func (x *OrderLookupRequest) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

type OrderInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	OrderSn       string                 `protobuf:"bytes,3,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	PayType       string                 `protobuf:"bytes,4,opt,name=payType,proto3" json:"payType,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Post          string                 `protobuf:"bytes,6,opt,name=post,proto3" json:"post,omitempty"`
	Address       string                 `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	Name          string                 `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty"`
	Mobile        string                 `protobuf:"bytes,10,opt,name=mobile,proto3" json:"mobile,omitempty"`
	AddTime       string                 `protobuf:"bytes,11,opt,name=addTime,proto3" json:"addTime,omitempty"`
	TradeNo       string                 `protobuf:"bytes,12,opt,name=tradeNo,proto3" json:"tradeNo,omitempty"`
	PayTime       int64                  `protobuf:"varint,13,opt,name=payTime,proto3" json:"payTime,omitempty"`
	TotalFen      int64                  `protobuf:"varint,14,opt,name=totalFen,proto3" json:"totalFen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderInfoResponse) Reset() {
	*x = OrderInfoResponse{}
	mi := &file_order_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfoResponse) ProtoMessage() {}

func (x *OrderInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfoResponse.ProtoReflect.Descriptor instead.
func (*OrderInfoResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{18}
}

func (x *OrderInfoResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderInfoResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderInfoResponse) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *OrderInfoResponse) GetPayType() string {
	if x != nil {
		return x.PayType
	}
	return ""
}

func (x *OrderInfoResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderInfoResponse) GetPost() string {
	if x != nil {
		return x.Post
	}
	return ""
}

func (x *OrderInfoResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *OrderInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderInfoResponse) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *OrderInfoResponse) GetAddTime() string {
	if x != nil {
		return x.AddTime
	}
	return ""
}

func (x *OrderInfoResponse) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *OrderInfoResponse) GetPayTime() int64 {
	if x != nil {
		return x.PayTime
	}
	return 0
}

func (x *OrderInfoResponse) GetTotalFen() int64 {
	if x != nil {
		return x.TotalFen
	}
	return 0
}

type ShopCartInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	GoodsId       int32                  `protobuf:"varint,3,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	Nums          int32                  `protobuf:"varint,4,opt,name=nums,proto3" json:"nums,omitempty"`
	Checked       bool                   `protobuf:"varint,5,opt,name=checked,proto3" json:"checked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopCartInfoResponse) Reset() {
	*x = ShopCartInfoResponse{}
	mi := &file_order_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopCartInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopCartInfoResponse) ProtoMessage() {}

func (x *ShopCartInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopCartInfoResponse.ProtoReflect.Descriptor instead.
func (*ShopCartInfoResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{19}
}

func (x *ShopCartInfoResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ShopCartInfoResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ShopCartInfoResponse) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *ShopCartInfoResponse) GetNums() int32 {
	if x != nil {
		return x.Nums
	}
	return 0
}

func (x *ShopCartInfoResponse) GetChecked() bool {
	if x != nil {
		return x.Checked
	}
	return false
}

type OrderItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       int32                  `protobuf:"varint,2,opt,name=orderId,proto3" json:"orderId,omitempty"`
	GoodsId       int32                  `protobuf:"varint,3,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	GoodsName     string                 `protobuf:"bytes,4,opt,name=goodsName,proto3" json:"goodsName,omitempty"`
	GoodsImage    string                 `protobuf:"bytes,5,opt,name=goodsImage,proto3" json:"goodsImage,omitempty"`
	Nums          int32                  `protobuf:"varint,7,opt,name=nums,proto3" json:"nums,omitempty"`
	GoodsPriceFen int64                  `protobuf:"varint,8,opt,name=goodsPriceFen,proto3" json:"goodsPriceFen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemResponse) Reset() {
	*x = OrderItemResponse{}
	mi := &file_order_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemResponse) ProtoMessage() {}

func (x *OrderItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemResponse.ProtoReflect.Descriptor instead.
func (*OrderItemResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{20}
}

func (x *OrderItemResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderItemResponse) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderItemResponse) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *OrderItemResponse) GetGoodsName() string {
	if x != nil {
		return x.GoodsName
	}
	return ""
}

func (x *OrderItemResponse) GetGoodsImage() string {
	if x != nil {
		return x.GoodsImage
	}
	return ""
}

func (x *OrderItemResponse) GetNums() int32 {
	if x != nil {
		return x.Nums
	}
	return 0
}

func (x *OrderItemResponse) GetGoodsPriceFen() int64 {
	if x != nil {
		return x.GoodsPriceFen
	}
	return 0
}

type OrderInfoDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderInfo     *OrderInfoResponse     `protobuf:"bytes,1,opt,name=orderInfo,proto3" json:"orderInfo,omitempty"`
	Goods         []*OrderItemResponse   `protobuf:"bytes,2,rep,name=goods,proto3" json:"goods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderInfoDetailResponse) Reset() {
	*x = OrderInfoDetailResponse{}
	mi := &file_order_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfoDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfoDetailResponse) ProtoMessage() {}

func (x *OrderInfoDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfoDetailResponse.ProtoReflect.Descriptor instead.
func (*OrderInfoDetailResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{21}
}

func (x *OrderInfoDetailResponse) GetOrderInfo() *OrderInfoResponse {
	if x != nil {
		return x.OrderInfo
	}
	return nil
}

func (x *OrderInfoDetailResponse) GetGoods() []*OrderItemResponse {
	if x != nil {
		return x.Goods
	}
	return nil
}

type OrderStatusLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       int32                  `protobuf:"varint,2,opt,name=orderId,proto3" json:"orderId,omitempty"`
	OrderSn       string                 `protobuf:"bytes,3,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	FromStatus    string                 `protobuf:"bytes,4,opt,name=fromStatus,proto3" json:"fromStatus,omitempty"`
	ToStatus      string                 `protobuf:"bytes,5,opt,name=toStatus,proto3" json:"toStatus,omitempty"`
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	Source        string                 `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	Operator      string                 `protobuf:"bytes,8,opt,name=operator,proto3" json:"operator,omitempty"`
	AddTime       string                 `protobuf:"bytes,9,opt,name=addTime,proto3" json:"addTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderStatusLogResponse) Reset() {
	*x = OrderStatusLogResponse{}
	mi := &file_order_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderStatusLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStatusLogResponse) ProtoMessage() {}

func (x *OrderStatusLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStatusLogResponse.ProtoReflect.Descriptor instead.
func (*OrderStatusLogResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{22}
}

func (x *OrderStatusLogResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderStatusLogResponse) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderStatusLogResponse) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *OrderStatusLogResponse) GetFromStatus() string {
	if x != nil {
		return x.FromStatus
	}
	return ""
}

func (x *OrderStatusLogResponse) GetToStatus() string {
	if x != nil {
		return x.ToStatus
	}
	return ""
}

func (x *OrderStatusLogResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *OrderStatusLogResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *OrderStatusLogResponse) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *OrderStatusLogResponse) GetAddTime() string {
	if x != nil {
		return x.AddTime
	}
	return ""
}

type OrderStatusLogListResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Total         int32                     `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data          []*OrderStatusLogResponse `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderStatusLogListResponse) Reset() {
	*x = OrderStatusLogListResponse{}
	mi := &file_order_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderStatusLogListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStatusLogListResponse) ProtoMessage() {}

func (x *OrderStatusLogListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStatusLogListResponse.ProtoReflect.Descriptor instead.
func (*OrderStatusLogListResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{23}
}

func (x *OrderStatusLogListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *OrderStatusLogListResponse) GetData() []*OrderStatusLogResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type OrderFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Pages         int32                  `protobuf:"varint,2,opt,name=pages,proto3" json:"pages,omitempty"`
	PagePerNums   int32                  `protobuf:"varint,3,opt,name=pagePerNums,proto3" json:"pagePerNums,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderFilterRequest) Reset() {
	*x = OrderFilterRequest{}
	mi := &file_order_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderFilterRequest) ProtoMessage() {}

func (x *OrderFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderFilterRequest.ProtoReflect.Descriptor instead.
func (*OrderFilterRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{24}
}

func (x *OrderFilterRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderFilterRequest) GetPages() int32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *OrderFilterRequest) GetPagePerNums() int32 {
	if x != nil {
		return x.PagePerNums
	}
	return 0
}

type OrderListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data          []*OrderInfoResponse   `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderListResponse) Reset() {
	*x = OrderListResponse{}
	mi := &file_order_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderListResponse) ProtoMessage() {}

func (x *OrderListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderListResponse.ProtoReflect.Descriptor instead.
func (*OrderListResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{25}
}

func (x *OrderListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *OrderListResponse) GetData() []*OrderInfoResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type CartItemListResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Total         int32                   `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data          []*ShopCartInfoResponse `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItemListResponse) Reset() {
	*x = CartItemListResponse{}
	mi := &file_order_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItemListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItemListResponse) ProtoMessage() {}

func (x *CartItemListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItemListResponse.ProtoReflect.Descriptor instead.
func (*CartItemListResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{26}
}

func (x *CartItemListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CartItemListResponse) GetData() []*ShopCartInfoResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xf5\x01\n" +
	"\x13PaymentEventRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x18\n" +
	"\aeventId\x18\x02 \x01(\tR\aeventId\x12\x18\n" +
	"\aorderSn\x18\x03 \x01(\tR\aorderSn\x12\x18\n" +
	"\atradeNo\x18\x04 \x01(\tR\atradeNo\x12\x1c\n" +
	"\teventType\x18\x05 \x01(\tR\teventType\x12,\n" +
	"\x11providerAmountFen\x18\x06 \x01(\x03R\x11providerAmountFen\x12(\n" +
	"\x0frefundAmountFen\x18\a \x01(\x03R\x0frefundAmountFen\"\xaa\x01\n" +
	"\x14PaymentEventResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x1c\n" +
	"\tcompleted\x18\x03 \x01(\bR\tcompleted\x12&\n" +
	"\x0eorderAmountFen\x18\x04 \x01(\x03R\x0eorderAmountFen\x12 \n" +
	"\vorderStatus\x18\x05 \x01(\tR\vorderStatus\"i\n" +
	"\x1bCompletePaymentEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12 \n" +
	"\verrorDetail\x18\x03 \x01(\tR\verrorDetail\"\x8b\x01\n" +
	"\x17PaymentEventListRequest\x12\x18\n" +
	"\aorderSn\x18\x01 \x01(\tR\aorderSn\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x05R\bpageSize\x12&\n" +
	"\x0emismatchesOnly\x18\x04 \x01(\bR\x0emismatchesOnly\"\xa8\x03\n" +
	"\x12PaymentEventRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x18\n" +
	"\aeventId\x18\x03 \x01(\tR\aeventId\x12\x18\n" +
	"\aorderSn\x18\x04 \x01(\tR\aorderSn\x12\x18\n" +
	"\atradeNo\x18\x05 \x01(\tR\atradeNo\x12\x1c\n" +
	"\teventType\x18\x06 \x01(\tR\teventType\x12&\n" +
	"\x0eorderAmountFen\x18\a \x01(\x03R\x0eorderAmountFen\x12,\n" +
	"\x11providerAmountFen\x18\b \x01(\x03R\x11providerAmountFen\x12(\n" +
	"\x0frefundAmountFen\x18\t \x01(\x03R\x0frefundAmountFen\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12 \n" +
	"\verrorDetail\x18\v \x01(\tR\verrorDetail\x12\x1e\n" +
	"\n" +
	"receivedAt\x18\f \x01(\x03R\n" +
	"receivedAt\x12 \n" +
	"\vcompletedAt\x18\r \x01(\x03R\vcompletedAt\"\x7f\n" +
	"\x18PaymentEventListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12'\n" +
	"\x04data\x18\x02 \x03(\v2\x13.PaymentEventRecordR\x04data\x12$\n" +
	"\rmismatchCount\x18\x03 \x01(\x05R\rmismatchCount\"\x80\x01\n" +
	"\x16ClaimRefundJobsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12 \n" +
	"\vmaxAttempts\x18\x02 \x01(\x05R\vmaxAttempts\x12.\n" +
	"\x12lockTimeoutSeconds\x18\x03 \x01(\x03R\x12lockTimeoutSeconds\"\xf1\x01\n" +
	"\tRefundJob\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12(\n" +
	"\x0frefundRequestId\x18\x02 \x01(\x03R\x0frefundRequestId\x12\x18\n" +
	"\aorderSn\x18\x03 \x01(\tR\aorderSn\x12\x18\n" +
	"\atradeNo\x18\x04 \x01(\tR\atradeNo\x12\x1c\n" +
	"\tamountFen\x18\x05 \x01(\x03R\tamountFen\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x12$\n" +
	"\rcorrelationId\x18\a \x01(\tR\rcorrelationId\x12\x1a\n" +
	"\battempts\x18\b \x01(\x05R\battempts\"9\n" +
	"\x17ClaimRefundJobsResponse\x12\x1e\n" +
	"\x04jobs\x18\x01 \x03(\v2\n" +
	".RefundJobR\x04jobs\"\xf8\x01\n" +
	"\x18CompleteRefundJobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12*\n" +
	"\x10providerRefundId\x18\x04 \x01(\tR\x10providerRefundId\x12&\n" +
	"\x0eproviderStatus\x18\x05 \x01(\tR\x0eproviderStatus\x12 \n" +
	"\verrorDetail\x18\x06 \x01(\tR\verrorDetail\x12 \n" +
	"\vmaxAttempts\x18\a \x01(\x05R\vmaxAttempts\"\xbf\x01\n" +
	"\x13ProviderTransaction\x12\x18\n" +
	"\aeventId\x18\x01 \x01(\tR\aeventId\x12\x18\n" +
	"\aorderSn\x18\x02 \x01(\tR\aorderSn\x12\x18\n" +
	"\atradeNo\x18\x03 \x01(\tR\atradeNo\x12\x1c\n" +
	"\teventType\x18\x04 \x01(\tR\teventType\x12\x1c\n" +
	"\tamountFen\x18\x05 \x01(\x03R\tamountFen\x12\x1e\n" +
	"\n" +
	"occurredAt\x18\x06 \x01(\x03R\n" +
	"occurredAt\"\xb0\x01\n" +
	"\x18ReconcilePaymentsRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12 \n" +
	"\vwindowStart\x18\x02 \x01(\x03R\vwindowStart\x12\x1c\n" +
	"\twindowEnd\x18\x03 \x01(\x03R\twindowEnd\x128\n" +
	"\ftransactions\x18\x04 \x03(\v2\x14.ProviderTransactionR\ftransactions\"{\n" +
	"\x19ReconcilePaymentsResponse\x12\x14\n" +
	"\x05runId\x18\x01 \x01(\x03R\x05runId\x12\"\n" +
	"\fcheckedCount\x18\x02 \x01(\x05R\fcheckedCount\x12$\n" +
	"\rmismatchCount\x18\x03 \x01(\x05R\rmismatchCount\"\x1a\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\xc5\x02\n" +
	"\vOrderStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\aorderSn\x18\x02 \x01(\tR\aorderSn\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\apayType\x18\x04 \x01(\tR\apayType\x12\x18\n" +
	"\atradeNo\x18\x05 \x01(\tR\atradeNo\x12\x18\n" +
	"\apayTime\x18\x06 \x01(\x03R\apayTime\x12 \n" +
	"\vactorUserId\x18\a \x01(\x05R\vactorUserId\x12(\n" +
	"\x0frefundAmountFen\x18\b \x01(\x03R\x0frefundAmountFen\x12\x16\n" +
	"\x06reason\x18\t \x01(\tR\x06reason\x12$\n" +
	"\rcorrelationId\x18\n" +
	" \x01(\tR\rcorrelationId\x12\x1c\n" +
	"\trequestId\x18\v \x01(\tR\trequestId\"\xf7\x01\n" +
	"\x0fCartItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x05R\x06userId\x12\x18\n" +
	"\agoodsId\x18\x03 \x01(\x05R\agoodsId\x12\x1c\n" +
	"\tgoodsName\x18\x04 \x01(\tR\tgoodsName\x12\x1e\n" +
	"\n" +
	"goodsImage\x18\x05 \x01(\tR\n" +
	"goodsImage\x12\x12\n" +
	"\x04nums\x18\a \x01(\x05R\x04nums\x12\x18\n" +
	"\achecked\x18\b \x01(\bR\achecked\x12$\n" +
	"\rgoodsPriceFen\x18\t \x01(\x03R\rgoodsPriceFenJ\x04\b\x06\x10\aR\n" +
	"goodsPrice\"\xde\x01\n" +
	"\fOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x05R\x06userId\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x16\n" +
	"\x06mobile\x18\x05 \x01(\tR\x06mobile\x12\x12\n" +
	"\x04post\x18\x06 \x01(\tR\x04post\x12\x18\n" +
	"\aorderSn\x18\a \x01(\tR\aorderSn\x122\n" +
	"\n" +
	"orderItems\x18\b \x03(\v2\x12.OrderItemResponseR\n" +
	"orderItems\".\n" +
	"\x12OrderLookupRequest\x12\x18\n" +
	"\aorderSn\x18\x01 \x01(\tR\aorderSn\"\xd8\x02\n" +
	"\x11OrderInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x05R\x06userId\x12\x18\n" +
	"\aorderSn\x18\x03 \x01(\tR\aorderSn\x12\x18\n" +
	"\apayType\x18\x04 \x01(\tR\apayType\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x12\n" +
	"\x04post\x18\x06 \x01(\tR\x04post\x12\x18\n" +
	"\aaddress\x18\b \x01(\tR\aaddress\x12\x12\n" +
	"\x04name\x18\t \x01(\tR\x04name\x12\x16\n" +
	"\x06mobile\x18\n" +
	" \x01(\tR\x06mobile\x12\x18\n" +
	"\aaddTime\x18\v \x01(\tR\aaddTime\x12\x18\n" +
	"\atradeNo\x18\f \x01(\tR\atradeNo\x12\x18\n" +
	"\apayTime\x18\r \x01(\x03R\apayTime\x12\x1a\n" +
	"\btotalFen\x18\x0e \x01(\x03R\btotalFenJ\x04\b\a\x10\bR\x05total\"\x86\x01\n" +
	"\x14ShopCartInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x05R\x06userId\x12\x18\n" +
	"\agoodsId\x18\x03 \x01(\x05R\agoodsId\x12\x12\n" +
	"\x04nums\x18\x04 \x01(\x05R\x04nums\x12\x18\n" +
	"\achecked\x18\x05 \x01(\bR\achecked\"\xe1\x01\n" +
	"\x11OrderItemResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\aorderId\x18\x02 \x01(\x05R\aorderId\x12\x18\n" +
	"\agoodsId\x18\x03 \x01(\x05R\agoodsId\x12\x1c\n" +
	"\tgoodsName\x18\x04 \x01(\tR\tgoodsName\x12\x1e\n" +
	"\n" +
	"goodsImage\x18\x05 \x01(\tR\n" +
	"goodsImage\x12\x12\n" +
	"\x04nums\x18\a \x01(\x05R\x04nums\x12$\n" +
	"\rgoodsPriceFen\x18\b \x01(\x03R\rgoodsPriceFenJ\x04\b\x06\x10\aR\n" +
	"goodsPrice\"u\n" +
	"\x17OrderInfoDetailResponse\x120\n" +
	"\torderInfo\x18\x01 \x01(\v2\x12.OrderInfoResponseR\torderInfo\x12(\n" +
	"\x05goods\x18\x02 \x03(\v2\x12.OrderItemResponseR\x05goods\"\xfe\x01\n" +
	"\x16OrderStatusLogResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\aorderId\x18\x02 \x01(\x05R\aorderId\x12\x18\n" +
	"\aorderSn\x18\x03 \x01(\tR\aorderSn\x12\x1e\n" +
	"\n" +
	"fromStatus\x18\x04 \x01(\tR\n" +
	"fromStatus\x12\x1a\n" +
	"\btoStatus\x18\x05 \x01(\tR\btoStatus\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x12\x16\n" +
	"\x06source\x18\a \x01(\tR\x06source\x12\x1a\n" +
	"\boperator\x18\b \x01(\tR\boperator\x12\x18\n" +
	"\aaddTime\x18\t \x01(\tR\aaddTime\"_\n" +
	"\x1aOrderStatusLogListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12+\n" +
	"\x04data\x18\x02 \x03(\v2\x17.OrderStatusLogResponseR\x04data\"d\n" +
	"\x12OrderFilterRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x05R\x06userId\x12\x14\n" +
	"\x05pages\x18\x02 \x01(\x05R\x05pages\x12 \n" +
	"\vpagePerNums\x18\x03 \x01(\x05R\vpagePerNums\"Q\n" +
	"\x11OrderListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12&\n" +
	"\x04data\x18\x02 \x03(\v2\x12.OrderInfoResponseR\x04data\"W\n" +
	"\x14CartItemListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12)\n" +
	"\x04data\x18\x02 \x03(\v2\x15.ShopCartInfoResponseR\x04data2\xec\b\n" +
	"\x05Order\x120\n" +
	"\fCartItemList\x12\t.UserInfo\x1a\x15.CartItemListResponse\x129\n" +
	"\x0eCreateCartItem\x12\x10.CartItemRequest\x1a\x15.ShopCartInfoResponse\x12:\n" +
	"\x0eUpdateCartItem\x12\x10.CartItemRequest\x1a\x16.google.protobuf.Empty\x12:\n" +
	"\x0eDeleteCartItem\x12\x10.CartItemRequest\x1a\x16.google.protobuf.Empty\x124\n" +
	"\vCreateOrder\x12\r.OrderRequest\x1a\x16.google.protobuf.Empty\x127\n" +
	"\x0eCreateOrderCom\x12\r.OrderRequest\x1a\x16.google.protobuf.Empty\x124\n" +
	"\vSubmitOrder\x12\r.OrderRequest\x1a\x16.google.protobuf.Empty\x124\n" +
	"\tOrderList\x12\x13.OrderFilterRequest\x1a\x12.OrderListResponse\x126\n" +
	"\vOrderDetail\x12\r.OrderRequest\x1a\x18.OrderInfoDetailResponse\x12=\n" +
	"\x0fOrderStatusLogs\x12\r.OrderRequest\x1a\x1b.OrderStatusLogListResponse\x12=\n" +
	"\fGetOrderBySn\x12\x13.OrderLookupRequest\x1a\x18.OrderInfoDetailResponse\x129\n" +
	"\x11UpdateOrderStatus\x12\f.OrderStatus\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\x11BeginPaymentEvent\x12\x14.PaymentEventRequest\x1a\x15.PaymentEventResponse\x12L\n" +
	"\x14CompletePaymentEvent\x12\x1c.CompletePaymentEventRequest\x1a\x16.google.protobuf.Empty\x12H\n" +
	"\x11ListPaymentEvents\x12\x18.PaymentEventListRequest\x1a\x19.PaymentEventListResponse\x12D\n" +
	"\x0fClaimRefundJobs\x12\x17.ClaimRefundJobsRequest\x1a\x18.ClaimRefundJobsResponse\x12F\n" +
	"\x11CompleteRefundJob\x12\x19.CompleteRefundJobRequest\x1a\x16.google.protobuf.Empty\x12J\n" +
	"\x11ReconcilePayments\x12\x19.ReconcilePaymentsRequest\x1a\x1a.ReconcilePaymentsResponseB\tZ\a.;protob\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_order_proto_goTypes = []any{
	(*PaymentEventRequest)(nil),         // 0: PaymentEventRequest
	(*PaymentEventResponse)(nil),        // 1: PaymentEventResponse
	(*CompletePaymentEventRequest)(nil), // 2: CompletePaymentEventRequest
	(*PaymentEventListRequest)(nil),     // 3: PaymentEventListRequest
	(*PaymentEventRecord)(nil),          // 4: PaymentEventRecord
	(*PaymentEventListResponse)(nil),    // 5: PaymentEventListResponse
	(*ClaimRefundJobsRequest)(nil),      // 6: ClaimRefundJobsRequest
	(*RefundJob)(nil),                   // 7: RefundJob
	(*ClaimRefundJobsResponse)(nil),     // 8: ClaimRefundJobsResponse
	(*CompleteRefundJobRequest)(nil),    // 9: CompleteRefundJobRequest
	(*ProviderTransaction)(nil),         // 10: ProviderTransaction
	(*ReconcilePaymentsRequest)(nil),    // 11: ReconcilePaymentsRequest
	(*ReconcilePaymentsResponse)(nil),   // 12: ReconcilePaymentsResponse
	(*UserInfo)(nil),                    // 13: UserInfo
	(*OrderStatus)(nil),                 // 14: OrderStatus
	(*CartItemRequest)(nil),             // 15: CartItemRequest
	(*OrderRequest)(nil),                // 16: OrderRequest
	(*OrderLookupRequest)(nil),          // 17: OrderLookupRequest
	(*OrderInfoResponse)(nil),           // 18: OrderInfoResponse
	(*ShopCartInfoResponse)(nil),        // 19: ShopCartInfoResponse
	(*OrderItemResponse)(nil),           // 20: OrderItemResponse
	(*OrderInfoDetailResponse)(nil),     // 21: OrderInfoDetailResponse
	(*OrderStatusLogResponse)(nil),      // 22: OrderStatusLogResponse
	(*OrderStatusLogListResponse)(nil),  // 23: OrderStatusLogListResponse
	(*OrderFilterRequest)(nil),          // 24: OrderFilterRequest
	(*OrderListResponse)(nil),           // 25: OrderListResponse
	(*CartItemListResponse)(nil),        // 26: CartItemListResponse
	(*emptypb.Empty)(nil),               // 27: google.protobuf.Empty
}
var file_order_proto_depIdxs = []int32{
	4,  // 0: PaymentEventListResponse.data:type_name -> PaymentEventRecord
	7,  // 1: ClaimRefundJobsResponse.jobs:type_name -> RefundJob
	10, // 2: ReconcilePaymentsRequest.transactions:type_name -> ProviderTransaction
	20, // 3: OrderRequest.orderItems:type_name -> OrderItemResponse
	18, // 4: OrderInfoDetailResponse.orderInfo:type_name -> OrderInfoResponse
	20, // 5: OrderInfoDetailResponse.goods:type_name -> OrderItemResponse
	22, // 6: OrderStatusLogListResponse.data:type_name -> OrderStatusLogResponse
	18, // 7: OrderListResponse.data:type_name -> OrderInfoResponse
	19, // 8: CartItemListResponse.data:type_name -> ShopCartInfoResponse
	13, // 9: Order.CartItemList:input_type -> UserInfo
	15, // 10: Order.CreateCartItem:input_type -> CartItemRequest
	15, // 11: Order.UpdateCartItem:input_type -> CartItemRequest
	15, // 12: Order.DeleteCartItem:input_type -> CartItemRequest
	16, // 13: Order.CreateOrder:input_type -> OrderRequest
	16, // 14: Order.CreateOrderCom:input_type -> OrderRequest
	16, // 15: Order.SubmitOrder:input_type -> OrderRequest
	24, // 16: Order.OrderList:input_type -> OrderFilterRequest
	16, // 17: Order.OrderDetail:input_type -> OrderRequest
	16, // 18: Order.OrderStatusLogs:input_type -> OrderRequest
	17, // 19: Order.GetOrderBySn:input_type -> OrderLookupRequest
	14, // 20: Order.UpdateOrderStatus:input_type -> OrderStatus
	0,  // 21: Order.BeginPaymentEvent:input_type -> PaymentEventRequest
	2,  // 22: Order.CompletePaymentEvent:input_type -> CompletePaymentEventRequest
	3,  // 23: Order.ListPaymentEvents:input_type -> PaymentEventListRequest
	6,  // 24: Order.ClaimRefundJobs:input_type -> ClaimRefundJobsRequest
	9,  // 25: Order.CompleteRefundJob:input_type -> CompleteRefundJobRequest
	11, // 26: Order.ReconcilePayments:input_type -> ReconcilePaymentsRequest
	26, // 27: Order.CartItemList:output_type -> CartItemListResponse
	19, // 28: Order.CreateCartItem:output_type -> ShopCartInfoResponse
	27, // 29: Order.UpdateCartItem:output_type -> google.protobuf.Empty
	27, // 30: Order.DeleteCartItem:output_type -> google.protobuf.Empty
	27, // 31: Order.CreateOrder:output_type -> google.protobuf.Empty
	27, // 32: Order.CreateOrderCom:output_type -> google.protobuf.Empty
	27, // 33: Order.SubmitOrder:output_type -> google.protobuf.Empty
	25, // 34: Order.OrderList:output_type -> OrderListResponse
	21, // 35: Order.OrderDetail:output_type -> OrderInfoDetailResponse
	23, // 36: Order.OrderStatusLogs:output_type -> OrderStatusLogListResponse
	21, // 37: Order.GetOrderBySn:output_type -> OrderInfoDetailResponse
	27, // 38: Order.UpdateOrderStatus:output_type -> google.protobuf.Empty
	1,  // 39: Order.BeginPaymentEvent:output_type -> PaymentEventResponse
	27, // 40: Order.CompletePaymentEvent:output_type -> google.protobuf.Empty
	5,  // 41: Order.ListPaymentEvents:output_type -> PaymentEventListResponse
	8,  // 42: Order.ClaimRefundJobs:output_type -> ClaimRefundJobsResponse
	27, // 43: Order.CompleteRefundJob:output_type -> google.protobuf.Empty
	12, // 44: Order.ReconcilePayments:output_type -> ReconcilePaymentsResponse
	27, // [27:45] is the sub-list for method output_type
	9,  // [9:27] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
