// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package srv

import (
	"goshop/app/pkg/options"
	"goshop/app/user/srv/internal/controller/user"
	db2 "goshop/app/user/srv/internal/data/v1/db"
	"goshop/app/user/srv/internal/service/v1"
	"goshop/gmicro/app"
	"goshop/pkg/log"
)

// Injectors from wire.go:

func initApp(nacosOptions *options.NacosOptions, logOptions *log.Options, serverOptions *options.ServerOptions, registryOptions *options.RegistryOptions, telemetryOptions *options.TelemetryOptions, mySQLOptions *options.MySQLOptions) (*app.App, error) {
	registrar := NewRegistrar(registryOptions)
	gormDB, err := db2.GetDBFactoryOr(mySQLOptions)
	if err != nil {
		return nil, err
	}
	userStore := db2.NewUsers(gormDB)
	userSrv := v1.NewUserService(userStore)
	userServer := user.NewUserServer(userSrv)
	nacosDataSource, err := NewNacosDataSource(nacosOptions)
	if err != nil {
		return nil, err
	}
	server, err := NewUserRPCServer(telemetryOptions, serverOptions, userServer, nacosDataSource)
	if err != nil {
		return nil, err
	}
	appApp, err := NewUserApp(logOptions, registrar, serverOptions, server)
	if err != nil {
		return nil, err
	}
	return appApp, nil
}
