// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package srv

import (
	"goshop/app/pkg/options"
	"goshop/app/user/srv/internal/controller/user"
	"goshop/app/user/srv/internal/data/v1/db"
	"goshop/app/user/srv/internal/service/v1"
	"goshop/gmicro/app"
	"goshop/gmicro/server/rpcserver"
)

// Injectors from wire.go:

func initApp(nacosOptions *options.NacosOptions, serverOptions *options.ServerOptions, registryOptions *options.RegistryOptions, rpcSecurityOptions *rpcserver.SecurityPolicy, telemetryOptions *options.TelemetryOptions, mySQLOptions *options.MySQLOptions) (*app.App, error) {
	registrar, err := NewRegistrar(registryOptions)
	if err != nil {
		return nil, err
	}
	gormDB, err := db.GetDBFactoryOr(mySQLOptions)
	if err != nil {
		return nil, err
	}
	userStore := db.NewUsers(gormDB)
	userSrv := v1.NewUserService(userStore)
	userServer := user.NewUserServer(userSrv)
	server, err := NewUserRPCServer(telemetryOptions, serverOptions, nacosOptions, rpcSecurityOptions, userServer)
	if err != nil {
		return nil, err
	}
	appApp, err := NewUserApp(registrar, serverOptions, server)
	if err != nil {
		return nil, err
	}
	return appApp, nil
}
