// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: review.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	OrderSn       string                 `protobuf:"bytes,2,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	GoodsId       int32                  `protobuf:"varint,3,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	Rating        int32                  `protobuf:"varint,4,opt,name=rating,proto3" json:"rating,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReviewRequest) Reset() {
	*x = CreateReviewRequest{}
	mi := &file_review_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReviewRequest) ProtoMessage() {}

func (x *CreateReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReviewRequest.ProtoReflect.Descriptor instead.
func (*CreateReviewRequest) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{0}
}

func (x *CreateReviewRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateReviewRequest) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *CreateReviewRequest) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *CreateReviewRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *CreateReviewRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type AppendReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ReviewId      int64                  `protobuf:"varint,2,opt,name=reviewId,proto3" json:"reviewId,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendReviewRequest) Reset() {
	*x = AppendReviewRequest{}
	mi := &file_review_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendReviewRequest) ProtoMessage() {}

func (x *AppendReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendReviewRequest.ProtoReflect.Descriptor instead.
func (*AppendReviewRequest) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{1}
}

func (x *AppendReviewRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AppendReviewRequest) GetReviewId() int64 {
	if x != nil {
		return x.ReviewId
	}
	return 0
}

func (x *AppendReviewRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ModerateReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReviewId      int64                  `protobuf:"varint,1,opt,name=reviewId,proto3" json:"reviewId,omitempty"`
	Decision      string                 `protobuf:"bytes,2,opt,name=decision,proto3" json:"decision,omitempty"`
	ActorUserId   int32                  `protobuf:"varint,3,opt,name=actorUserId,proto3" json:"actorUserId,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModerateReviewRequest) Reset() {
	*x = ModerateReviewRequest{}
	mi := &file_review_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModerateReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModerateReviewRequest) ProtoMessage() {}

func (x *ModerateReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModerateReviewRequest.ProtoReflect.Descriptor instead.
func (*ModerateReviewRequest) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{2}
}

func (x *ModerateReviewRequest) GetReviewId() int64 {
	if x != nil {
		return x.ReviewId
	}
	return 0
}

func (x *ModerateReviewRequest) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *ModerateReviewRequest) GetActorUserId() int32 {
	if x != nil {
		return x.ActorUserId
	}
	return 0
}

func (x *ModerateReviewRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ModerateReviewRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ReplyReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReviewId      int64                  `protobuf:"varint,1,opt,name=reviewId,proto3" json:"reviewId,omitempty"`
	ActorUserId   int32                  `protobuf:"varint,2,opt,name=actorUserId,proto3" json:"actorUserId,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=requestId,proto3" json:"requestId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyReviewRequest) Reset() {
	*x = ReplyReviewRequest{}
	mi := &file_review_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyReviewRequest) ProtoMessage() {}

func (x *ReplyReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyReviewRequest.ProtoReflect.Descriptor instead.
func (*ReplyReviewRequest) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{3}
}

func (x *ReplyReviewRequest) GetReviewId() int64 {
	if x != nil {
		return x.ReviewId
	}
	return 0
}

func (x *ReplyReviewRequest) GetActorUserId() int32 {
	if x != nil {
		return x.ActorUserId
	}
	return 0
}

func (x *ReplyReviewRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ReplyReviewRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ListReviewsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsId       int32                  `protobuf:"varint,1,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReviewsRequest) Reset() {
	*x = ListReviewsRequest{}
	mi := &file_review_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReviewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReviewsRequest) ProtoMessage() {}

func (x *ListReviewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReviewsRequest.ProtoReflect.Descriptor instead.
func (*ListReviewsRequest) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{4}
}

func (x *ListReviewsRequest) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *ListReviewsRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListReviewsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListReviewsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListReviewsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetRatingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsId       int32                  `protobuf:"varint,1,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRatingRequest) Reset() {
	*x = GetRatingRequest{}
	mi := &file_review_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatingRequest) ProtoMessage() {}

func (x *GetRatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatingRequest.ProtoReflect.Descriptor instead.
func (*GetRatingRequest) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{5}
}

func (x *GetRatingRequest) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

type RebuildRatingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsId       int32                  `protobuf:"varint,1,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	ActorUserId   int32                  `protobuf:"varint,2,opt,name=actorUserId,proto3" json:"actorUserId,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=requestId,proto3" json:"requestId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebuildRatingRequest) Reset() {
	*x = RebuildRatingRequest{}
	mi := &file_review_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebuildRatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebuildRatingRequest) ProtoMessage() {}

func (x *RebuildRatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebuildRatingRequest.ProtoReflect.Descriptor instead.
func (*RebuildRatingRequest) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{6}
}

func (x *RebuildRatingRequest) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *RebuildRatingRequest) GetActorUserId() int32 {
	if x != nil {
		return x.ActorUserId
	}
	return 0
}

func (x *RebuildRatingRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	OrderSn       string                 `protobuf:"bytes,3,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	GoodsId       int32                  `protobuf:"varint,4,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	Rating        int32                  `protobuf:"varint,5,opt,name=rating,proto3" json:"rating,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	AppendContent string                 `protobuf:"bytes,8,opt,name=appendContent,proto3" json:"appendContent,omitempty"`
	MerchantReply string                 `protobuf:"bytes,9,opt,name=merchantReply,proto3" json:"merchantReply,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,10,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewResponse) Reset() {
	*x = ReviewResponse{}
	mi := &file_review_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewResponse) ProtoMessage() {}

func (x *ReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewResponse.ProtoReflect.Descriptor instead.
func (*ReviewResponse) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{7}
}

func (x *ReviewResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReviewResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReviewResponse) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *ReviewResponse) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *ReviewResponse) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *ReviewResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ReviewResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReviewResponse) GetAppendContent() string {
	if x != nil {
		return x.AppendContent
	}
	return ""
}

func (x *ReviewResponse) GetMerchantReply() string {
	if x != nil {
		return x.MerchantReply
	}
	return ""
}

func (x *ReviewResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ReviewListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data          []*ReviewResponse      `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewListResponse) Reset() {
	*x = ReviewListResponse{}
	mi := &file_review_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewListResponse) ProtoMessage() {}

func (x *ReviewListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewListResponse.ProtoReflect.Descriptor instead.
func (*ReviewListResponse) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{8}
}

func (x *ReviewListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ReviewListResponse) GetData() []*ReviewResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type RatingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsId       int32                  `protobuf:"varint,1,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	ApprovedCount int64                  `protobuf:"varint,2,opt,name=approvedCount,proto3" json:"approvedCount,omitempty"`
	RatingSum     int64                  `protobuf:"varint,3,opt,name=ratingSum,proto3" json:"ratingSum,omitempty"`
	AverageMilli  int32                  `protobuf:"varint,4,opt,name=averageMilli,proto3" json:"averageMilli,omitempty"`
	RebuiltAt     int64                  `protobuf:"varint,5,opt,name=rebuiltAt,proto3" json:"rebuiltAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RatingResponse) Reset() {
	*x = RatingResponse{}
	mi := &file_review_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RatingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatingResponse) ProtoMessage() {}

func (x *RatingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatingResponse.ProtoReflect.Descriptor instead.
func (*RatingResponse) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{9}
}

func (x *RatingResponse) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *RatingResponse) GetApprovedCount() int64 {
	if x != nil {
		return x.ApprovedCount
	}
	return 0
}

func (x *RatingResponse) GetRatingSum() int64 {
	if x != nil {
		return x.RatingSum
	}
	return 0
}

func (x *RatingResponse) GetAverageMilli() int32 {
	if x != nil {
		return x.AverageMilli
	}
	return 0
}

func (x *RatingResponse) GetRebuiltAt() int64 {
	if x != nil {
		return x.RebuiltAt
	}
	return 0
}

var File_review_proto protoreflect.FileDescriptor

const file_review_proto_rawDesc = "" +
	"\n" +
	"\freview.proto\"\x93\x01\n" +
	"\x13CreateReviewRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x05R\x06userId\x12\x18\n" +
	"\aorderSn\x18\x02 \x01(\tR\aorderSn\x12\x18\n" +
	"\agoodsId\x18\x03 \x01(\x05R\agoodsId\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\x05R\x06rating\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\"c\n" +
	"\x13AppendReviewRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x05R\x06userId\x12\x1a\n" +
	"\breviewId\x18\x02 \x01(\x03R\breviewId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"\xa7\x01\n" +
	"\x15ModerateReviewRequest\x12\x1a\n" +
	"\breviewId\x18\x01 \x01(\x03R\breviewId\x12\x1a\n" +
	"\bdecision\x18\x02 \x01(\tR\bdecision\x12 \n" +
	"\vactorUserId\x18\x03 \x01(\x05R\vactorUserId\x12\x1c\n" +
	"\trequestId\x18\x04 \x01(\tR\trequestId\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"\x8a\x01\n" +
	"\x12ReplyReviewRequest\x12\x1a\n" +
	"\breviewId\x18\x01 \x01(\x03R\breviewId\x12 \n" +
	"\vactorUserId\x18\x02 \x01(\x05R\vactorUserId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1c\n" +
	"\trequestId\x18\x04 \x01(\tR\trequestId\"\x8e\x01\n" +
	"\x12ListReviewsRequest\x12\x18\n" +
	"\agoodsId\x18\x01 \x01(\x05R\agoodsId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x05R\x06userId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x05 \x01(\x05R\bpageSize\",\n" +
	"\x10GetRatingRequest\x12\x18\n" +
	"\agoodsId\x18\x01 \x01(\x05R\agoodsId\"p\n" +
	"\x14RebuildRatingRequest\x12\x18\n" +
	"\agoodsId\x18\x01 \x01(\x05R\agoodsId\x12 \n" +
	"\vactorUserId\x18\x02 \x01(\x05R\vactorUserId\x12\x1c\n" +
	"\trequestId\x18\x03 \x01(\tR\trequestId\"\xa0\x02\n" +
	"\x0eReviewResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x05R\x06userId\x12\x18\n" +
	"\aorderSn\x18\x03 \x01(\tR\aorderSn\x12\x18\n" +
	"\agoodsId\x18\x04 \x01(\x05R\agoodsId\x12\x16\n" +
	"\x06rating\x18\x05 \x01(\x05R\x06rating\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12$\n" +
	"\rappendContent\x18\b \x01(\tR\rappendContent\x12$\n" +
	"\rmerchantReply\x18\t \x01(\tR\rmerchantReply\x12\x1c\n" +
	"\tcreatedAt\x18\n" +
	" \x01(\x03R\tcreatedAt\"O\n" +
	"\x12ReviewListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12#\n" +
	"\x04data\x18\x02 \x03(\v2\x0f.ReviewResponseR\x04data\"\xb0\x01\n" +
	"\x0eRatingResponse\x12\x18\n" +
	"\agoodsId\x18\x01 \x01(\x05R\agoodsId\x12$\n" +
	"\rapprovedCount\x18\x02 \x01(\x03R\rapprovedCount\x12\x1c\n" +
	"\tratingSum\x18\x03 \x01(\x03R\tratingSum\x12\"\n" +
	"\faverageMilli\x18\x04 \x01(\x05R\faverageMilli\x12\x1c\n" +
	"\trebuiltAt\x18\x05 \x01(\x03R\trebuiltAt2\x89\x03\n" +
	"\x06Review\x125\n" +
	"\fCreateReview\x12\x14.CreateReviewRequest\x1a\x0f.ReviewResponse\x125\n" +
	"\fAppendReview\x12\x14.AppendReviewRequest\x1a\x0f.ReviewResponse\x127\n" +
	"\vListReviews\x12\x13.ListReviewsRequest\x1a\x13.ReviewListResponse\x129\n" +
	"\x0eModerateReview\x12\x16.ModerateReviewRequest\x1a\x0f.ReviewResponse\x123\n" +
	"\vReplyReview\x12\x13.ReplyReviewRequest\x1a\x0f.ReviewResponse\x12/\n" +
	"\tGetRating\x12\x11.GetRatingRequest\x1a\x0f.RatingResponse\x127\n" +
	"\rRebuildRating\x12\x15.RebuildRatingRequest\x1a\x0f.RatingResponseB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_review_proto_rawDescOnce sync.Once
	file_review_proto_rawDescData []byte
)

func file_review_proto_rawDescGZIP() []byte {
	file_review_proto_rawDescOnce.Do(func() {
		file_review_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_review_proto_rawDesc), len(file_review_proto_rawDesc)))
	})
	return file_review_proto_rawDescData
}

var file_review_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_review_proto_goTypes = []any{
	(*CreateReviewRequest)(nil),   // 0: CreateReviewRequest
	(*AppendReviewRequest)(nil),   // 1: AppendReviewRequest
	(*ModerateReviewRequest)(nil), // 2: ModerateReviewRequest
	(*ReplyReviewRequest)(nil),    // 3: ReplyReviewRequest
	(*ListReviewsRequest)(nil),    // 4: ListReviewsRequest
	(*GetRatingRequest)(nil),      // 5: GetRatingRequest
	(*RebuildRatingRequest)(nil),  // 6: RebuildRatingRequest
	(*ReviewResponse)(nil),        // 7: ReviewResponse
	(*ReviewListResponse)(nil),    // 8: ReviewListResponse
	(*RatingResponse)(nil),        // 9: RatingResponse
}
var file_review_proto_depIdxs = []int32{
	7, // 0: ReviewListResponse.data:type_name -> ReviewResponse
	0, // 1: Review.CreateReview:input_type -> CreateReviewRequest
	1, // 2: Review.AppendReview:input_type -> AppendReviewRequest
	4, // 3: Review.ListReviews:input_type -> ListReviewsRequest
	2, // 4: Review.ModerateReview:input_type -> ModerateReviewRequest
	3, // 5: Review.ReplyReview:input_type -> ReplyReviewRequest
	5, // 6: Review.GetRating:input_type -> GetRatingRequest
	6, // 7: Review.RebuildRating:input_type -> RebuildRatingRequest
	7, // 8: Review.CreateReview:output_type -> ReviewResponse
	7, // 9: Review.AppendReview:output_type -> ReviewResponse
	8, // 10: Review.ListReviews:output_type -> ReviewListResponse
	7, // 11: Review.ModerateReview:output_type -> ReviewResponse
	7, // 12: Review.ReplyReview:output_type -> ReviewResponse
	9, // 13: Review.GetRating:output_type -> RatingResponse
	9, // 14: Review.RebuildRating:output_type -> RatingResponse
	8, // [8:15] is the sub-list for method output_type
	1, // [1:8] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_review_proto_init() }
func file_review_proto_init() {
	if File_review_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_review_proto_rawDesc), len(file_review_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_review_proto_goTypes,
		DependencyIndexes: file_review_proto_depIdxs,
		MessageInfos:      file_review_proto_msgTypes,
	}.Build()
	File_review_proto = out.File
	file_review_proto_goTypes = nil
	file_review_proto_depIdxs = nil
}
