// Code generated by protoc-gen-go-gin. DO NOT EDIT.

package proto

import (
	gin "github.com/gin-gonic/gin"
	http "net/http"
)

type ReviewHttpServer struct {
	server ReviewServer
	router gin.IRouter
}

func RegisterReviewServerHTTPServer(srv ReviewServer, r gin.IRouter) {
	s := ReviewHttpServer{
		server: srv,
		router: r,
	}
	s.RegisterService()
}

func (s *ReviewHttpServer) CreateReview_0(c *gin.Context) {
	var in CreateReviewRequest

	if err := c.ShouldBindJSON(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	out, err := s.server.CreateReview(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *ReviewHttpServer) AppendReview_0(c *gin.Context) {
	var in AppendReviewRequest

	if err := c.ShouldBindJSON(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	out, err := s.server.AppendReview(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *ReviewHttpServer) ListReviews_0(c *gin.Context) {
	var in ListReviewsRequest

	if err := c.ShouldBindJSON(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	out, err := s.server.ListReviews(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *ReviewHttpServer) ModerateReview_0(c *gin.Context) {
	var in ModerateReviewRequest

	if err := c.ShouldBindJSON(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	out, err := s.server.ModerateReview(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *ReviewHttpServer) ReplyReview_0(c *gin.Context) {
	var in ReplyReviewRequest

	if err := c.ShouldBindJSON(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	out, err := s.server.ReplyReview(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *ReviewHttpServer) GetRating_0(c *gin.Context) {
	var in GetRatingRequest

	if err := c.ShouldBindJSON(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	out, err := s.server.GetRating(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *ReviewHttpServer) RebuildRating_0(c *gin.Context) {
	var in RebuildRatingRequest

	if err := c.ShouldBindJSON(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	out, err := s.server.RebuildRating(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *ReviewHttpServer) RegisterService() {

	s.router.Handle("POST", "", s.CreateReview_0)

	s.router.Handle("POST", "", s.AppendReview_0)

	s.router.Handle("POST", "", s.ListReviews_0)

	s.router.Handle("POST", "", s.ModerateReview_0)

	s.router.Handle("POST", "", s.ReplyReview_0)

	s.router.Handle("POST", "", s.GetRating_0)

	s.router.Handle("POST", "", s.RebuildRating_0)

}
